//
// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.
//

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: wal_quorum_service.proto

package qwalpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HealthCheckResponse_Status int32

const (
	HealthCheckResponse_UNKNOWN     HealthCheckResponse_Status = 0
	HealthCheckResponse_SERVING     HealthCheckResponse_Status = 1
	HealthCheckResponse_NOT_SERVING HealthCheckResponse_Status = 2
)

// Enum value maps for HealthCheckResponse_Status.
var (
	HealthCheckResponse_Status_name = map[int32]string{
		0: "UNKNOWN",
		1: "SERVING",
		2: "NOT_SERVING",
	}
	HealthCheckResponse_Status_value = map[string]int32{
		"UNKNOWN":     0,
		"SERVING":     1,
		"NOT_SERVING": 2,
	}
)

func (x HealthCheckResponse_Status) Enum() *HealthCheckResponse_Status {
	p := new(HealthCheckResponse_Status)
	*p = x
	return p
}

func (x HealthCheckResponse_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HealthCheckResponse_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_wal_quorum_service_proto_enumTypes[0].Descriptor()
}

func (HealthCheckResponse_Status) Type() protoreflect.EnumType {
	return &file_wal_quorum_service_proto_enumTypes[0]
}

func (x HealthCheckResponse_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HealthCheckResponse_Status.Descriptor instead.
func (HealthCheckResponse_Status) EnumDescriptor() ([]byte, []int) {
	return file_wal_quorum_service_proto_rawDescGZIP(), []int{10, 0}
}

// Unique identity for a WAL segment.
type SegmentId struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// UUID assigned by the originator when the segment is opened.
	Uuid string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	// WAL path within the Accumulo namespace (e.g. /accumulo/wal/<addr>/<uuid>).
	WalPath       string `protobuf:"bytes,2,opt,name=wal_path,json=walPath,proto3" json:"wal_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SegmentId) Reset() {
	*x = SegmentId{}
	mi := &file_wal_quorum_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SegmentId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SegmentId) ProtoMessage() {}

func (x *SegmentId) ProtoReflect() protoreflect.Message {
	mi := &file_wal_quorum_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SegmentId.ProtoReflect.Descriptor instead.
func (*SegmentId) Descriptor() ([]byte, []int) {
	return file_wal_quorum_service_proto_rawDescGZIP(), []int{0}
}

func (x *SegmentId) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *SegmentId) GetWalPath() string {
	if x != nil {
		return x.WalPath
	}
	return ""
}

type OpenSegmentRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	SegmentId *SegmentId             `protobuf:"bytes,1,opt,name=segment_id,json=segmentId,proto3" json:"segment_id,omitempty"`
	// Pod name of the TServer that owns this WAL.
	OriginatorPod string `protobuf:"bytes,2,opt,name=originator_pod,json=originatorPod,proto3" json:"originator_pod,omitempty"`
	// Desired replication factor (typically 3).
	ReplicationFactor uint32 `protobuf:"varint,3,opt,name=replication_factor,json=replicationFactor,proto3" json:"replication_factor,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *OpenSegmentRequest) Reset() {
	*x = OpenSegmentRequest{}
	mi := &file_wal_quorum_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenSegmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenSegmentRequest) ProtoMessage() {}

func (x *OpenSegmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wal_quorum_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenSegmentRequest.ProtoReflect.Descriptor instead.
func (*OpenSegmentRequest) Descriptor() ([]byte, []int) {
	return file_wal_quorum_service_proto_rawDescGZIP(), []int{1}
}

func (x *OpenSegmentRequest) GetSegmentId() *SegmentId {
	if x != nil {
		return x.SegmentId
	}
	return nil
}

func (x *OpenSegmentRequest) GetOriginatorPod() string {
	if x != nil {
		return x.OriginatorPod
	}
	return ""
}

func (x *OpenSegmentRequest) GetReplicationFactor() uint32 {
	if x != nil {
		return x.ReplicationFactor
	}
	return 0
}

type OpenSegmentResponse struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Success bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error   string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	// Peers that acknowledged the PrepareSegment call.
	PreparedPeers []string `protobuf:"bytes,3,rep,name=prepared_peers,json=preparedPeers,proto3" json:"prepared_peers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenSegmentResponse) Reset() {
	*x = OpenSegmentResponse{}
	mi := &file_wal_quorum_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenSegmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenSegmentResponse) ProtoMessage() {}

func (x *OpenSegmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wal_quorum_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenSegmentResponse.ProtoReflect.Descriptor instead.
func (*OpenSegmentResponse) Descriptor() ([]byte, []int) {
	return file_wal_quorum_service_proto_rawDescGZIP(), []int{2}
}

func (x *OpenSegmentResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *OpenSegmentResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *OpenSegmentResponse) GetPreparedPeers() []string {
	if x != nil {
		return x.PreparedPeers
	}
	return nil
}

type WriteEntryRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	SegmentId *SegmentId             `protobuf:"bytes,1,opt,name=segment_id,json=segmentId,proto3" json:"segment_id,omitempty"`
	// Monotonically increasing sequence number within the segment.
	SequenceNum uint64 `protobuf:"varint,2,opt,name=sequence_num,json=sequenceNum,proto3" json:"sequence_num,omitempty"`
	// Raw WAL entry bytes.
	Data []byte `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	// CRC-32C checksum of data.
	Checksum      uint32 `protobuf:"varint,4,opt,name=checksum,proto3" json:"checksum,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteEntryRequest) Reset() {
	*x = WriteEntryRequest{}
	mi := &file_wal_quorum_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteEntryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteEntryRequest) ProtoMessage() {}

func (x *WriteEntryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wal_quorum_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteEntryRequest.ProtoReflect.Descriptor instead.
func (*WriteEntryRequest) Descriptor() ([]byte, []int) {
	return file_wal_quorum_service_proto_rawDescGZIP(), []int{3}
}

func (x *WriteEntryRequest) GetSegmentId() *SegmentId {
	if x != nil {
		return x.SegmentId
	}
	return nil
}

func (x *WriteEntryRequest) GetSequenceNum() uint64 {
	if x != nil {
		return x.SequenceNum
	}
	return 0
}

func (x *WriteEntryRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *WriteEntryRequest) GetChecksum() uint32 {
	if x != nil {
		return x.Checksum
	}
	return 0
}

type WriteEntryResponse struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	SegmentId *SegmentId             `protobuf:"bytes,1,opt,name=segment_id,json=segmentId,proto3" json:"segment_id,omitempty"`
	// Sequence number being acknowledged.
	AckedSequenceNum uint64 `protobuf:"varint,2,opt,name=acked_sequence_num,json=ackedSequenceNum,proto3" json:"acked_sequence_num,omitempty"`
	// Number of replicas (including local) that persisted this entry.
	QuorumCount uint32 `protobuf:"varint,3,opt,name=quorum_count,json=quorumCount,proto3" json:"quorum_count,omitempty"`
	// Current write offset in the segment after this entry.
	CommittedOffset int64 `protobuf:"varint,4,opt,name=committed_offset,json=committedOffset,proto3" json:"committed_offset,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *WriteEntryResponse) Reset() {
	*x = WriteEntryResponse{}
	mi := &file_wal_quorum_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteEntryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteEntryResponse) ProtoMessage() {}

func (x *WriteEntryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wal_quorum_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteEntryResponse.ProtoReflect.Descriptor instead.
func (*WriteEntryResponse) Descriptor() ([]byte, []int) {
	return file_wal_quorum_service_proto_rawDescGZIP(), []int{4}
}

func (x *WriteEntryResponse) GetSegmentId() *SegmentId {
	if x != nil {
		return x.SegmentId
	}
	return nil
}

func (x *WriteEntryResponse) GetAckedSequenceNum() uint64 {
	if x != nil {
		return x.AckedSequenceNum
	}
	return 0
}

func (x *WriteEntryResponse) GetQuorumCount() uint32 {
	if x != nil {
		return x.QuorumCount
	}
	return 0
}

func (x *WriteEntryResponse) GetCommittedOffset() int64 {
	if x != nil {
		return x.CommittedOffset
	}
	return 0
}

type SyncSegmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SegmentId     *SegmentId             `protobuf:"bytes,1,opt,name=segment_id,json=segmentId,proto3" json:"segment_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncSegmentRequest) Reset() {
	*x = SyncSegmentRequest{}
	mi := &file_wal_quorum_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncSegmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncSegmentRequest) ProtoMessage() {}

func (x *SyncSegmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wal_quorum_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncSegmentRequest.ProtoReflect.Descriptor instead.
func (*SyncSegmentRequest) Descriptor() ([]byte, []int) {
	return file_wal_quorum_service_proto_rawDescGZIP(), []int{5}
}

func (x *SyncSegmentRequest) GetSegmentId() *SegmentId {
	if x != nil {
		return x.SegmentId
	}
	return nil
}

type SyncSegmentResponse struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Success bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error   string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	// Durable offset after sync across the quorum.
	SyncedOffset  int64 `protobuf:"varint,3,opt,name=synced_offset,json=syncedOffset,proto3" json:"synced_offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncSegmentResponse) Reset() {
	*x = SyncSegmentResponse{}
	mi := &file_wal_quorum_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncSegmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncSegmentResponse) ProtoMessage() {}

func (x *SyncSegmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wal_quorum_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncSegmentResponse.ProtoReflect.Descriptor instead.
func (*SyncSegmentResponse) Descriptor() ([]byte, []int) {
	return file_wal_quorum_service_proto_rawDescGZIP(), []int{6}
}

func (x *SyncSegmentResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SyncSegmentResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *SyncSegmentResponse) GetSyncedOffset() int64 {
	if x != nil {
		return x.SyncedOffset
	}
	return 0
}

type CloseSegmentRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	SegmentId *SegmentId             `protobuf:"bytes,1,opt,name=segment_id,json=segmentId,proto3" json:"segment_id,omitempty"`
	// SHA-256 digest of the full segment computed by the TServer.
	FinalChecksum []byte `protobuf:"bytes,2,opt,name=final_checksum,json=finalChecksum,proto3" json:"final_checksum,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseSegmentRequest) Reset() {
	*x = CloseSegmentRequest{}
	mi := &file_wal_quorum_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseSegmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseSegmentRequest) ProtoMessage() {}

func (x *CloseSegmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wal_quorum_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseSegmentRequest.ProtoReflect.Descriptor instead.
func (*CloseSegmentRequest) Descriptor() ([]byte, []int) {
	return file_wal_quorum_service_proto_rawDescGZIP(), []int{7}
}

func (x *CloseSegmentRequest) GetSegmentId() *SegmentId {
	if x != nil {
		return x.SegmentId
	}
	return nil
}

func (x *CloseSegmentRequest) GetFinalChecksum() []byte {
	if x != nil {
		return x.FinalChecksum
	}
	return nil
}

type CloseSegmentResponse struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Success bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error   string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	// Total bytes in the sealed segment.
	SegmentSize int64 `protobuf:"varint,3,opt,name=segment_size,json=segmentSize,proto3" json:"segment_size,omitempty"`
	// GCS object name where the segment will be uploaded.
	GcsObjectPath string `protobuf:"bytes,4,opt,name=gcs_object_path,json=gcsObjectPath,proto3" json:"gcs_object_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseSegmentResponse) Reset() {
	*x = CloseSegmentResponse{}
	mi := &file_wal_quorum_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseSegmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseSegmentResponse) ProtoMessage() {}

func (x *CloseSegmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wal_quorum_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseSegmentResponse.ProtoReflect.Descriptor instead.
func (*CloseSegmentResponse) Descriptor() ([]byte, []int) {
	return file_wal_quorum_service_proto_rawDescGZIP(), []int{8}
}

func (x *CloseSegmentResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CloseSegmentResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *CloseSegmentResponse) GetSegmentSize() int64 {
	if x != nil {
		return x.SegmentSize
	}
	return 0
}

func (x *CloseSegmentResponse) GetGcsObjectPath() string {
	if x != nil {
		return x.GcsObjectPath
	}
	return ""
}

type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_wal_quorum_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wal_quorum_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_wal_quorum_service_proto_rawDescGZIP(), []int{9}
}

type HealthCheckResponse struct {
	state           protoimpl.MessageState     `protogen:"open.v1"`
	Status          HealthCheckResponse_Status `protobuf:"varint,1,opt,name=status,proto3,enum=org.apache.accumulo.server.fs.pvc.wal.HealthCheckResponse_Status" json:"status,omitempty"`
	OpenSegments    uint32                     `protobuf:"varint,2,opt,name=open_segments,json=openSegments,proto3" json:"open_segments,omitempty"`
	PeerConnections uint32                     `protobuf:"varint,3,opt,name=peer_connections,json=peerConnections,proto3" json:"peer_connections,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_wal_quorum_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wal_quorum_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_wal_quorum_service_proto_rawDescGZIP(), []int{10}
}

func (x *HealthCheckResponse) GetStatus() HealthCheckResponse_Status {
	if x != nil {
		return x.Status
	}
	return HealthCheckResponse_UNKNOWN
}

func (x *HealthCheckResponse) GetOpenSegments() uint32 {
	if x != nil {
		return x.OpenSegments
	}
	return 0
}

func (x *HealthCheckResponse) GetPeerConnections() uint32 {
	if x != nil {
		return x.PeerConnections
	}
	return 0
}

type PrepareSegmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SegmentId     *SegmentId             `protobuf:"bytes,1,opt,name=segment_id,json=segmentId,proto3" json:"segment_id,omitempty"`
	OriginatorPod string                 `protobuf:"bytes,2,opt,name=originator_pod,json=originatorPod,proto3" json:"originator_pod,omitempty"`
	// Expected maximum size hint for pre-allocation (bytes).
	ExpectedSize  int64 `protobuf:"varint,3,opt,name=expected_size,json=expectedSize,proto3" json:"expected_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrepareSegmentRequest) Reset() {
	*x = PrepareSegmentRequest{}
	mi := &file_wal_quorum_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrepareSegmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrepareSegmentRequest) ProtoMessage() {}

func (x *PrepareSegmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wal_quorum_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrepareSegmentRequest.ProtoReflect.Descriptor instead.
func (*PrepareSegmentRequest) Descriptor() ([]byte, []int) {
	return file_wal_quorum_service_proto_rawDescGZIP(), []int{11}
}

func (x *PrepareSegmentRequest) GetSegmentId() *SegmentId {
	if x != nil {
		return x.SegmentId
	}
	return nil
}

func (x *PrepareSegmentRequest) GetOriginatorPod() string {
	if x != nil {
		return x.OriginatorPod
	}
	return ""
}

func (x *PrepareSegmentRequest) GetExpectedSize() int64 {
	if x != nil {
		return x.ExpectedSize
	}
	return 0
}

type PrepareSegmentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrepareSegmentResponse) Reset() {
	*x = PrepareSegmentResponse{}
	mi := &file_wal_quorum_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrepareSegmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrepareSegmentResponse) ProtoMessage() {}

func (x *PrepareSegmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wal_quorum_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrepareSegmentResponse.ProtoReflect.Descriptor instead.
func (*PrepareSegmentResponse) Descriptor() ([]byte, []int) {
	return file_wal_quorum_service_proto_rawDescGZIP(), []int{12}
}

func (x *PrepareSegmentResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PrepareSegmentResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ReplicateEntryRequest struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	SegmentId   *SegmentId             `protobuf:"bytes,1,opt,name=segment_id,json=segmentId,proto3" json:"segment_id,omitempty"`
	SequenceNum uint64                 `protobuf:"varint,2,opt,name=sequence_num,json=sequenceNum,proto3" json:"sequence_num,omitempty"`
	Data        []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	Checksum    uint32                 `protobuf:"varint,4,opt,name=checksum,proto3" json:"checksum,omitempty"`
	// Byte offset within the segment where this entry starts.
	Offset        int64 `protobuf:"varint,5,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplicateEntryRequest) Reset() {
	*x = ReplicateEntryRequest{}
	mi := &file_wal_quorum_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplicateEntryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicateEntryRequest) ProtoMessage() {}

func (x *ReplicateEntryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wal_quorum_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicateEntryRequest.ProtoReflect.Descriptor instead.
func (*ReplicateEntryRequest) Descriptor() ([]byte, []int) {
	return file_wal_quorum_service_proto_rawDescGZIP(), []int{13}
}

func (x *ReplicateEntryRequest) GetSegmentId() *SegmentId {
	if x != nil {
		return x.SegmentId
	}
	return nil
}

func (x *ReplicateEntryRequest) GetSequenceNum() uint64 {
	if x != nil {
		return x.SequenceNum
	}
	return 0
}

func (x *ReplicateEntryRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ReplicateEntryRequest) GetChecksum() uint32 {
	if x != nil {
		return x.Checksum
	}
	return 0
}

func (x *ReplicateEntryRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ReplicateEntryResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	SegmentId        *SegmentId             `protobuf:"bytes,1,opt,name=segment_id,json=segmentId,proto3" json:"segment_id,omitempty"`
	AckedSequenceNum uint64                 `protobuf:"varint,2,opt,name=acked_sequence_num,json=ackedSequenceNum,proto3" json:"acked_sequence_num,omitempty"`
	// Byte offset after writing this entry on the replica.
	PersistedOffset int64 `protobuf:"varint,3,opt,name=persisted_offset,json=persistedOffset,proto3" json:"persisted_offset,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ReplicateEntryResponse) Reset() {
	*x = ReplicateEntryResponse{}
	mi := &file_wal_quorum_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplicateEntryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicateEntryResponse) ProtoMessage() {}

func (x *ReplicateEntryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wal_quorum_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicateEntryResponse.ProtoReflect.Descriptor instead.
func (*ReplicateEntryResponse) Descriptor() ([]byte, []int) {
	return file_wal_quorum_service_proto_rawDescGZIP(), []int{14}
}

func (x *ReplicateEntryResponse) GetSegmentId() *SegmentId {
	if x != nil {
		return x.SegmentId
	}
	return nil
}

func (x *ReplicateEntryResponse) GetAckedSequenceNum() uint64 {
	if x != nil {
		return x.AckedSequenceNum
	}
	return 0
}

func (x *ReplicateEntryResponse) GetPersistedOffset() int64 {
	if x != nil {
		return x.PersistedOffset
	}
	return 0
}

type SealSegmentRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	SegmentId *SegmentId             `protobuf:"bytes,1,opt,name=segment_id,json=segmentId,proto3" json:"segment_id,omitempty"`
	// SHA-256 digest the originator computed; peer must match.
	ExpectedChecksum []byte `protobuf:"bytes,2,opt,name=expected_checksum,json=expectedChecksum,proto3" json:"expected_checksum,omitempty"`
	ExpectedSize     int64  `protobuf:"varint,3,opt,name=expected_size,json=expectedSize,proto3" json:"expected_size,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SealSegmentRequest) Reset() {
	*x = SealSegmentRequest{}
	mi := &file_wal_quorum_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SealSegmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SealSegmentRequest) ProtoMessage() {}

func (x *SealSegmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wal_quorum_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SealSegmentRequest.ProtoReflect.Descriptor instead.
func (*SealSegmentRequest) Descriptor() ([]byte, []int) {
	return file_wal_quorum_service_proto_rawDescGZIP(), []int{15}
}

func (x *SealSegmentRequest) GetSegmentId() *SegmentId {
	if x != nil {
		return x.SegmentId
	}
	return nil
}

func (x *SealSegmentRequest) GetExpectedChecksum() []byte {
	if x != nil {
		return x.ExpectedChecksum
	}
	return nil
}

func (x *SealSegmentRequest) GetExpectedSize() int64 {
	if x != nil {
		return x.ExpectedSize
	}
	return 0
}

type SealSegmentResponse struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Success bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error   string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	// Actual checksum computed by the peer.
	ActualChecksum []byte `protobuf:"bytes,3,opt,name=actual_checksum,json=actualChecksum,proto3" json:"actual_checksum,omitempty"`
	ActualSize     int64  `protobuf:"varint,4,opt,name=actual_size,json=actualSize,proto3" json:"actual_size,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SealSegmentResponse) Reset() {
	*x = SealSegmentResponse{}
	mi := &file_wal_quorum_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SealSegmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SealSegmentResponse) ProtoMessage() {}

func (x *SealSegmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wal_quorum_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SealSegmentResponse.ProtoReflect.Descriptor instead.
func (*SealSegmentResponse) Descriptor() ([]byte, []int) {
	return file_wal_quorum_service_proto_rawDescGZIP(), []int{16}
}

func (x *SealSegmentResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SealSegmentResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *SealSegmentResponse) GetActualChecksum() []byte {
	if x != nil {
		return x.ActualChecksum
	}
	return nil
}

func (x *SealSegmentResponse) GetActualSize() int64 {
	if x != nil {
		return x.ActualSize
	}
	return 0
}

type ReadSegmentRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	SegmentId *SegmentId             `protobuf:"bytes,1,opt,name=segment_id,json=segmentId,proto3" json:"segment_id,omitempty"`
	// Start reading from this offset (0 = beginning).
	Offset int64 `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	// Maximum bytes to read (0 = read to end).
	MaxBytes      int64 `protobuf:"varint,3,opt,name=max_bytes,json=maxBytes,proto3" json:"max_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadSegmentRequest) Reset() {
	*x = ReadSegmentRequest{}
	mi := &file_wal_quorum_service_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadSegmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadSegmentRequest) ProtoMessage() {}

func (x *ReadSegmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wal_quorum_service_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadSegmentRequest.ProtoReflect.Descriptor instead.
func (*ReadSegmentRequest) Descriptor() ([]byte, []int) {
	return file_wal_quorum_service_proto_rawDescGZIP(), []int{17}
}

func (x *ReadSegmentRequest) GetSegmentId() *SegmentId {
	if x != nil {
		return x.SegmentId
	}
	return nil
}

func (x *ReadSegmentRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ReadSegmentRequest) GetMaxBytes() int64 {
	if x != nil {
		return x.MaxBytes
	}
	return 0
}

type SegmentChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Offset        int64                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Last          bool                   `protobuf:"varint,3,opt,name=last,proto3" json:"last,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SegmentChunk) Reset() {
	*x = SegmentChunk{}
	mi := &file_wal_quorum_service_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SegmentChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SegmentChunk) ProtoMessage() {}

func (x *SegmentChunk) ProtoReflect() protoreflect.Message {
	mi := &file_wal_quorum_service_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SegmentChunk.ProtoReflect.Descriptor instead.
func (*SegmentChunk) Descriptor() ([]byte, []int) {
	return file_wal_quorum_service_proto_rawDescGZIP(), []int{18}
}

func (x *SegmentChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *SegmentChunk) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *SegmentChunk) GetLast() bool {
	if x != nil {
		return x.Last
	}
	return false
}

type ListSegmentsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional filter: only return segments for this originator.
	OriginatorPod string `protobuf:"bytes,1,opt,name=originator_pod,json=originatorPod,proto3" json:"originator_pod,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSegmentsRequest) Reset() {
	*x = ListSegmentsRequest{}
	mi := &file_wal_quorum_service_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSegmentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSegmentsRequest) ProtoMessage() {}

func (x *ListSegmentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wal_quorum_service_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSegmentsRequest.ProtoReflect.Descriptor instead.
func (*ListSegmentsRequest) Descriptor() ([]byte, []int) {
	return file_wal_quorum_service_proto_rawDescGZIP(), []int{19}
}

func (x *ListSegmentsRequest) GetOriginatorPod() string {
	if x != nil {
		return x.OriginatorPod
	}
	return ""
}

type ListSegmentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Segments      []*SegmentInfo         `protobuf:"bytes,1,rep,name=segments,proto3" json:"segments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSegmentsResponse) Reset() {
	*x = ListSegmentsResponse{}
	mi := &file_wal_quorum_service_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSegmentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSegmentsResponse) ProtoMessage() {}

func (x *ListSegmentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wal_quorum_service_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSegmentsResponse.ProtoReflect.Descriptor instead.
func (*ListSegmentsResponse) Descriptor() ([]byte, []int) {
	return file_wal_quorum_service_proto_rawDescGZIP(), []int{20}
}

func (x *ListSegmentsResponse) GetSegments() []*SegmentInfo {
	if x != nil {
		return x.Segments
	}
	return nil
}

type SegmentInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SegmentId     *SegmentId             `protobuf:"bytes,1,opt,name=segment_id,json=segmentId,proto3" json:"segment_id,omitempty"`
	OriginatorPod string                 `protobuf:"bytes,2,opt,name=originator_pod,json=originatorPod,proto3" json:"originator_pod,omitempty"`
	Size          int64                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	Sealed        bool                   `protobuf:"varint,4,opt,name=sealed,proto3" json:"sealed,omitempty"`
	// Milliseconds since epoch.
	CreatedAt     int64 `protobuf:"varint,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	SealedAt      int64 `protobuf:"varint,6,opt,name=sealed_at,json=sealedAt,proto3" json:"sealed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SegmentInfo) Reset() {
	*x = SegmentInfo{}
	mi := &file_wal_quorum_service_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SegmentInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SegmentInfo) ProtoMessage() {}

func (x *SegmentInfo) ProtoReflect() protoreflect.Message {
	mi := &file_wal_quorum_service_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SegmentInfo.ProtoReflect.Descriptor instead.
func (*SegmentInfo) Descriptor() ([]byte, []int) {
	return file_wal_quorum_service_proto_rawDescGZIP(), []int{21}
}

func (x *SegmentInfo) GetSegmentId() *SegmentId {
	if x != nil {
		return x.SegmentId
	}
	return nil
}

func (x *SegmentInfo) GetOriginatorPod() string {
	if x != nil {
		return x.OriginatorPod
	}
	return ""
}

func (x *SegmentInfo) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *SegmentInfo) GetSealed() bool {
	if x != nil {
		return x.Sealed
	}
	return false
}

func (x *SegmentInfo) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *SegmentInfo) GetSealedAt() int64 {
	if x != nil {
		return x.SealedAt
	}
	return 0
}

type PurgeSegmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SegmentId     *SegmentId             `protobuf:"bytes,1,opt,name=segment_id,json=segmentId,proto3" json:"segment_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PurgeSegmentRequest) Reset() {
	*x = PurgeSegmentRequest{}
	mi := &file_wal_quorum_service_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PurgeSegmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PurgeSegmentRequest) ProtoMessage() {}

func (x *PurgeSegmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wal_quorum_service_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PurgeSegmentRequest.ProtoReflect.Descriptor instead.
func (*PurgeSegmentRequest) Descriptor() ([]byte, []int) {
	return file_wal_quorum_service_proto_rawDescGZIP(), []int{22}
}

func (x *PurgeSegmentRequest) GetSegmentId() *SegmentId {
	if x != nil {
		return x.SegmentId
	}
	return nil
}

type PurgeSegmentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PurgeSegmentResponse) Reset() {
	*x = PurgeSegmentResponse{}
	mi := &file_wal_quorum_service_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PurgeSegmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PurgeSegmentResponse) ProtoMessage() {}

func (x *PurgeSegmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wal_quorum_service_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PurgeSegmentResponse.ProtoReflect.Descriptor instead.
func (*PurgeSegmentResponse) Descriptor() ([]byte, []int) {
	return file_wal_quorum_service_proto_rawDescGZIP(), []int{23}
}

func (x *PurgeSegmentResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PurgeSegmentResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_wal_quorum_service_proto protoreflect.FileDescriptor

const file_wal_quorum_service_proto_rawDesc = "" +
	"\n" +
	"\x18wal_quorum_service.proto\x12%org.apache.accumulo.server.fs.pvc.wal\":\n" +
	"\tSegmentId\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x19\n" +
	"\bwal_path\x18\x02 \x01(\tR\awalPath\"\xbb\x01\n" +
	"\x12OpenSegmentRequest\x12O\n" +
	"\n" +
	"segment_id\x18\x01 \x01(\v20.org.apache.accumulo.server.fs.pvc.wal.SegmentIdR\tsegmentId\x12%\n" +
	"\x0eoriginator_pod\x18\x02 \x01(\tR\roriginatorPod\x12-\n" +
	"\x12replication_factor\x18\x03 \x01(\rR\x11replicationFactor\"l\n" +
	"\x13OpenSegmentResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12%\n" +
	"\x0eprepared_peers\x18\x03 \x03(\tR\rpreparedPeers\"\xb7\x01\n" +
	"\x11WriteEntryRequest\x12O\n" +
	"\n" +
	"segment_id\x18\x01 \x01(\v20.org.apache.accumulo.server.fs.pvc.wal.SegmentIdR\tsegmentId\x12!\n" +
	"\fsequence_num\x18\x02 \x01(\x04R\vsequenceNum\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\x12\x1a\n" +
	"\bchecksum\x18\x04 \x01(\rR\bchecksum\"\xe1\x01\n" +
	"\x12WriteEntryResponse\x12O\n" +
	"\n" +
	"segment_id\x18\x01 \x01(\v20.org.apache.accumulo.server.fs.pvc.wal.SegmentIdR\tsegmentId\x12,\n" +
	"\x12acked_sequence_num\x18\x02 \x01(\x04R\x10ackedSequenceNum\x12!\n" +
	"\fquorum_count\x18\x03 \x01(\rR\vquorumCount\x12)\n" +
	"\x10committed_offset\x18\x04 \x01(\x03R\x0fcommittedOffset\"e\n" +
	"\x12SyncSegmentRequest\x12O\n" +
	"\n" +
	"segment_id\x18\x01 \x01(\v20.org.apache.accumulo.server.fs.pvc.wal.SegmentIdR\tsegmentId\"j\n" +
	"\x13SyncSegmentResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12#\n" +
	"\rsynced_offset\x18\x03 \x01(\x03R\fsyncedOffset\"\x8d\x01\n" +
	"\x13CloseSegmentRequest\x12O\n" +
	"\n" +
	"segment_id\x18\x01 \x01(\v20.org.apache.accumulo.server.fs.pvc.wal.SegmentIdR\tsegmentId\x12%\n" +
	"\x0efinal_checksum\x18\x02 \x01(\fR\rfinalChecksum\"\x91\x01\n" +
	"\x14CloseSegmentResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12!\n" +
	"\fsegment_size\x18\x03 \x01(\x03R\vsegmentSize\x12&\n" +
	"\x0fgcs_object_path\x18\x04 \x01(\tR\rgcsObjectPath\"\x14\n" +
	"\x12HealthCheckRequest\"\xf5\x01\n" +
	"\x13HealthCheckResponse\x12Y\n" +
	"\x06status\x18\x01 \x01(\x0e2A.org.apache.accumulo.server.fs.pvc.wal.HealthCheckResponse.StatusR\x06status\x12#\n" +
	"\ropen_segments\x18\x02 \x01(\rR\fopenSegments\x12)\n" +
	"\x10peer_connections\x18\x03 \x01(\rR\x0fpeerConnections\"3\n" +
	"\x06Status\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\v\n" +
	"\aSERVING\x10\x01\x12\x0f\n" +
	"\vNOT_SERVING\x10\x02\"\xb4\x01\n" +
	"\x15PrepareSegmentRequest\x12O\n" +
	"\n" +
	"segment_id\x18\x01 \x01(\v20.org.apache.accumulo.server.fs.pvc.wal.SegmentIdR\tsegmentId\x12%\n" +
	"\x0eoriginator_pod\x18\x02 \x01(\tR\roriginatorPod\x12#\n" +
	"\rexpected_size\x18\x03 \x01(\x03R\fexpectedSize\"H\n" +
	"\x16PrepareSegmentResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\xd3\x01\n" +
	"\x15ReplicateEntryRequest\x12O\n" +
	"\n" +
	"segment_id\x18\x01 \x01(\v20.org.apache.accumulo.server.fs.pvc.wal.SegmentIdR\tsegmentId\x12!\n" +
	"\fsequence_num\x18\x02 \x01(\x04R\vsequenceNum\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\x12\x1a\n" +
	"\bchecksum\x18\x04 \x01(\rR\bchecksum\x12\x16\n" +
	"\x06offset\x18\x05 \x01(\x03R\x06offset\"\xc2\x01\n" +
	"\x16ReplicateEntryResponse\x12O\n" +
	"\n" +
	"segment_id\x18\x01 \x01(\v20.org.apache.accumulo.server.fs.pvc.wal.SegmentIdR\tsegmentId\x12,\n" +
	"\x12acked_sequence_num\x18\x02 \x01(\x04R\x10ackedSequenceNum\x12)\n" +
	"\x10persisted_offset\x18\x03 \x01(\x03R\x0fpersistedOffset\"\xb7\x01\n" +
	"\x12SealSegmentRequest\x12O\n" +
	"\n" +
	"segment_id\x18\x01 \x01(\v20.org.apache.accumulo.server.fs.pvc.wal.SegmentIdR\tsegmentId\x12+\n" +
	"\x11expected_checksum\x18\x02 \x01(\fR\x10expectedChecksum\x12#\n" +
	"\rexpected_size\x18\x03 \x01(\x03R\fexpectedSize\"\x8f\x01\n" +
	"\x13SealSegmentResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12'\n" +
	"\x0factual_checksum\x18\x03 \x01(\fR\x0eactualChecksum\x12\x1f\n" +
	"\vactual_size\x18\x04 \x01(\x03R\n" +
	"actualSize\"\x9a\x01\n" +
	"\x12ReadSegmentRequest\x12O\n" +
	"\n" +
	"segment_id\x18\x01 \x01(\v20.org.apache.accumulo.server.fs.pvc.wal.SegmentIdR\tsegmentId\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x03R\x06offset\x12\x1b\n" +
	"\tmax_bytes\x18\x03 \x01(\x03R\bmaxBytes\"N\n" +
	"\fSegmentChunk\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x03R\x06offset\x12\x12\n" +
	"\x04last\x18\x03 \x01(\bR\x04last\"<\n" +
	"\x13ListSegmentsRequest\x12%\n" +
	"\x0eoriginator_pod\x18\x01 \x01(\tR\roriginatorPod\"f\n" +
	"\x14ListSegmentsResponse\x12N\n" +
	"\bsegments\x18\x01 \x03(\v22.org.apache.accumulo.server.fs.pvc.wal.SegmentInfoR\bsegments\"\xed\x01\n" +
	"\vSegmentInfo\x12O\n" +
	"\n" +
	"segment_id\x18\x01 \x01(\v20.org.apache.accumulo.server.fs.pvc.wal.SegmentIdR\tsegmentId\x12%\n" +
	"\x0eoriginator_pod\x18\x02 \x01(\tR\roriginatorPod\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x03R\x04size\x12\x16\n" +
	"\x06sealed\x18\x04 \x01(\bR\x06sealed\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\x03R\tcreatedAt\x12\x1b\n" +
	"\tsealed_at\x18\x06 \x01(\x03R\bsealedAt\"f\n" +
	"\x13PurgeSegmentRequest\x12O\n" +
	"\n" +
	"segment_id\x18\x01 \x01(\v20.org.apache.accumulo.server.fs.pvc.wal.SegmentIdR\tsegmentId\"F\n" +
	"\x14PurgeSegmentResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error2\xb9\x05\n" +
	"\x0eWalQuorumLocal\x12\x84\x01\n" +
	"\vOpenSegment\x129.org.apache.accumulo.server.fs.pvc.wal.OpenSegmentRequest\x1a:.org.apache.accumulo.server.fs.pvc.wal.OpenSegmentResponse\x12\x87\x01\n" +
	"\fWriteEntries\x128.org.apache.accumulo.server.fs.pvc.wal.WriteEntryRequest\x1a9.org.apache.accumulo.server.fs.pvc.wal.WriteEntryResponse(\x010\x01\x12\x84\x01\n" +
	"\vSyncSegment\x129.org.apache.accumulo.server.fs.pvc.wal.SyncSegmentRequest\x1a:.org.apache.accumulo.server.fs.pvc.wal.SyncSegmentResponse\x12\x87\x01\n" +
	"\fCloseSegment\x12:.org.apache.accumulo.server.fs.pvc.wal.CloseSegmentRequest\x1a;.org.apache.accumulo.server.fs.pvc.wal.CloseSegmentResponse\x12\x84\x01\n" +
	"\vHealthCheck\x129.org.apache.accumulo.server.fs.pvc.wal.HealthCheckRequest\x1a:.org.apache.accumulo.server.fs.pvc.wal.HealthCheckResponse2\xd1\x06\n" +
	"\rWalQuorumPeer\x12\x8d\x01\n" +
	"\x0ePrepareSegment\x12<.org.apache.accumulo.server.fs.pvc.wal.PrepareSegmentRequest\x1a=.org.apache.accumulo.server.fs.pvc.wal.PrepareSegmentResponse\x12\x93\x01\n" +
	"\x10ReplicateEntries\x12<.org.apache.accumulo.server.fs.pvc.wal.ReplicateEntryRequest\x1a=.org.apache.accumulo.server.fs.pvc.wal.ReplicateEntryResponse(\x010\x01\x12\x84\x01\n" +
	"\vSealSegment\x129.org.apache.accumulo.server.fs.pvc.wal.SealSegmentRequest\x1a:.org.apache.accumulo.server.fs.pvc.wal.SealSegmentResponse\x12\x7f\n" +
	"\vReadSegment\x129.org.apache.accumulo.server.fs.pvc.wal.ReadSegmentRequest\x1a3.org.apache.accumulo.server.fs.pvc.wal.SegmentChunk0\x01\x12\x87\x01\n" +
	"\fListSegments\x12:.org.apache.accumulo.server.fs.pvc.wal.ListSegmentsRequest\x1a;.org.apache.accumulo.server.fs.pvc.wal.ListSegmentsResponse\x12\x87\x01\n" +
	"\fPurgeSegment\x12:.org.apache.accumulo.server.fs.pvc.wal.PurgeSegmentRequest\x1a;.org.apache.accumulo.server.fs.pvc.wal.PurgeSegmentResponseBw\n" +
	"'org.apache.accumulo.server.fs.pvc.protoB\x15WalQuorumServiceProtoP\x01Z3github.com/accumulo/wal-quorum-sidecar/proto/qwalpbb\x06proto3"

var (
	file_wal_quorum_service_proto_rawDescOnce sync.Once
	file_wal_quorum_service_proto_rawDescData []byte
)

func file_wal_quorum_service_proto_rawDescGZIP() []byte {
	file_wal_quorum_service_proto_rawDescOnce.Do(func() {
		file_wal_quorum_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_wal_quorum_service_proto_rawDesc), len(file_wal_quorum_service_proto_rawDesc)))
	})
	return file_wal_quorum_service_proto_rawDescData
}

var file_wal_quorum_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_wal_quorum_service_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_wal_quorum_service_proto_goTypes = []any{
	(HealthCheckResponse_Status)(0), // 0: org.apache.accumulo.server.fs.pvc.wal.HealthCheckResponse.Status
	(*SegmentId)(nil),               // 1: org.apache.accumulo.server.fs.pvc.wal.SegmentId
	(*OpenSegmentRequest)(nil),      // 2: org.apache.accumulo.server.fs.pvc.wal.OpenSegmentRequest
	(*OpenSegmentResponse)(nil),     // 3: org.apache.accumulo.server.fs.pvc.wal.OpenSegmentResponse
	(*WriteEntryRequest)(nil),       // 4: org.apache.accumulo.server.fs.pvc.wal.WriteEntryRequest
	(*WriteEntryResponse)(nil),      // 5: org.apache.accumulo.server.fs.pvc.wal.WriteEntryResponse
	(*SyncSegmentRequest)(nil),      // 6: org.apache.accumulo.server.fs.pvc.wal.SyncSegmentRequest
	(*SyncSegmentResponse)(nil),     // 7: org.apache.accumulo.server.fs.pvc.wal.SyncSegmentResponse
	(*CloseSegmentRequest)(nil),     // 8: org.apache.accumulo.server.fs.pvc.wal.CloseSegmentRequest
	(*CloseSegmentResponse)(nil),    // 9: org.apache.accumulo.server.fs.pvc.wal.CloseSegmentResponse
	(*HealthCheckRequest)(nil),      // 10: org.apache.accumulo.server.fs.pvc.wal.HealthCheckRequest
	(*HealthCheckResponse)(nil),     // 11: org.apache.accumulo.server.fs.pvc.wal.HealthCheckResponse
	(*PrepareSegmentRequest)(nil),   // 12: org.apache.accumulo.server.fs.pvc.wal.PrepareSegmentRequest
	(*PrepareSegmentResponse)(nil),  // 13: org.apache.accumulo.server.fs.pvc.wal.PrepareSegmentResponse
	(*ReplicateEntryRequest)(nil),   // 14: org.apache.accumulo.server.fs.pvc.wal.ReplicateEntryRequest
	(*ReplicateEntryResponse)(nil),  // 15: org.apache.accumulo.server.fs.pvc.wal.ReplicateEntryResponse
	(*SealSegmentRequest)(nil),      // 16: org.apache.accumulo.server.fs.pvc.wal.SealSegmentRequest
	(*SealSegmentResponse)(nil),     // 17: org.apache.accumulo.server.fs.pvc.wal.SealSegmentResponse
	(*ReadSegmentRequest)(nil),      // 18: org.apache.accumulo.server.fs.pvc.wal.ReadSegmentRequest
	(*SegmentChunk)(nil),            // 19: org.apache.accumulo.server.fs.pvc.wal.SegmentChunk
	(*ListSegmentsRequest)(nil),     // 20: org.apache.accumulo.server.fs.pvc.wal.ListSegmentsRequest
	(*ListSegmentsResponse)(nil),    // 21: org.apache.accumulo.server.fs.pvc.wal.ListSegmentsResponse
	(*SegmentInfo)(nil),             // 22: org.apache.accumulo.server.fs.pvc.wal.SegmentInfo
	(*PurgeSegmentRequest)(nil),     // 23: org.apache.accumulo.server.fs.pvc.wal.PurgeSegmentRequest
	(*PurgeSegmentResponse)(nil),    // 24: org.apache.accumulo.server.fs.pvc.wal.PurgeSegmentResponse
}
var file_wal_quorum_service_proto_depIdxs = []int32{
	1,  // 0: org.apache.accumulo.server.fs.pvc.wal.OpenSegmentRequest.segment_id:type_name -> org.apache.accumulo.server.fs.pvc.wal.SegmentId
	1,  // 1: org.apache.accumulo.server.fs.pvc.wal.WriteEntryRequest.segment_id:type_name -> org.apache.accumulo.server.fs.pvc.wal.SegmentId
	1,  // 2: org.apache.accumulo.server.fs.pvc.wal.WriteEntryResponse.segment_id:type_name -> org.apache.accumulo.server.fs.pvc.wal.SegmentId
	1,  // 3: org.apache.accumulo.server.fs.pvc.wal.SyncSegmentRequest.segment_id:type_name -> org.apache.accumulo.server.fs.pvc.wal.SegmentId
	1,  // 4: org.apache.accumulo.server.fs.pvc.wal.CloseSegmentRequest.segment_id:type_name -> org.apache.accumulo.server.fs.pvc.wal.SegmentId
	0,  // 5: org.apache.accumulo.server.fs.pvc.wal.HealthCheckResponse.status:type_name -> org.apache.accumulo.server.fs.pvc.wal.HealthCheckResponse.Status
	1,  // 6: org.apache.accumulo.server.fs.pvc.wal.PrepareSegmentRequest.segment_id:type_name -> org.apache.accumulo.server.fs.pvc.wal.SegmentId
	1,  // 7: org.apache.accumulo.server.fs.pvc.wal.ReplicateEntryRequest.segment_id:type_name -> org.apache.accumulo.server.fs.pvc.wal.SegmentId
	1,  // 8: org.apache.accumulo.server.fs.pvc.wal.ReplicateEntryResponse.segment_id:type_name -> org.apache.accumulo.server.fs.pvc.wal.SegmentId
	1,  // 9: org.apache.accumulo.server.fs.pvc.wal.SealSegmentRequest.segment_id:type_name -> org.apache.accumulo.server.fs.pvc.wal.SegmentId
	1,  // 10: org.apache.accumulo.server.fs.pvc.wal.ReadSegmentRequest.segment_id:type_name -> org.apache.accumulo.server.fs.pvc.wal.SegmentId
	22, // 11: org.apache.accumulo.server.fs.pvc.wal.ListSegmentsResponse.segments:type_name -> org.apache.accumulo.server.fs.pvc.wal.SegmentInfo
	1,  // 12: org.apache.accumulo.server.fs.pvc.wal.SegmentInfo.segment_id:type_name -> org.apache.accumulo.server.fs.pvc.wal.SegmentId
	1,  // 13: org.apache.accumulo.server.fs.pvc.wal.PurgeSegmentRequest.segment_id:type_name -> org.apache.accumulo.server.fs.pvc.wal.SegmentId
	2,  // 14: org.apache.accumulo.server.fs.pvc.wal.WalQuorumLocal.OpenSegment:input_type -> org.apache.accumulo.server.fs.pvc.wal.OpenSegmentRequest
	4,  // 15: org.apache.accumulo.server.fs.pvc.wal.WalQuorumLocal.WriteEntries:input_type -> org.apache.accumulo.server.fs.pvc.wal.WriteEntryRequest
	6,  // 16: org.apache.accumulo.server.fs.pvc.wal.WalQuorumLocal.SyncSegment:input_type -> org.apache.accumulo.server.fs.pvc.wal.SyncSegmentRequest
	8,  // 17: org.apache.accumulo.server.fs.pvc.wal.WalQuorumLocal.CloseSegment:input_type -> org.apache.accumulo.server.fs.pvc.wal.CloseSegmentRequest
	10, // 18: org.apache.accumulo.server.fs.pvc.wal.WalQuorumLocal.HealthCheck:input_type -> org.apache.accumulo.server.fs.pvc.wal.HealthCheckRequest
	12, // 19: org.apache.accumulo.server.fs.pvc.wal.WalQuorumPeer.PrepareSegment:input_type -> org.apache.accumulo.server.fs.pvc.wal.PrepareSegmentRequest
	14, // 20: org.apache.accumulo.server.fs.pvc.wal.WalQuorumPeer.ReplicateEntries:input_type -> org.apache.accumulo.server.fs.pvc.wal.ReplicateEntryRequest
	16, // 21: org.apache.accumulo.server.fs.pvc.wal.WalQuorumPeer.SealSegment:input_type -> org.apache.accumulo.server.fs.pvc.wal.SealSegmentRequest
	18, // 22: org.apache.accumulo.server.fs.pvc.wal.WalQuorumPeer.ReadSegment:input_type -> org.apache.accumulo.server.fs.pvc.wal.ReadSegmentRequest
	20, // 23: org.apache.accumulo.server.fs.pvc.wal.WalQuorumPeer.ListSegments:input_type -> org.apache.accumulo.server.fs.pvc.wal.ListSegmentsRequest
	23, // 24: org.apache.accumulo.server.fs.pvc.wal.WalQuorumPeer.PurgeSegment:input_type -> org.apache.accumulo.server.fs.pvc.wal.PurgeSegmentRequest
	3,  // 25: org.apache.accumulo.server.fs.pvc.wal.WalQuorumLocal.OpenSegment:output_type -> org.apache.accumulo.server.fs.pvc.wal.OpenSegmentResponse
	5,  // 26: org.apache.accumulo.server.fs.pvc.wal.WalQuorumLocal.WriteEntries:output_type -> org.apache.accumulo.server.fs.pvc.wal.WriteEntryResponse
	7,  // 27: org.apache.accumulo.server.fs.pvc.wal.WalQuorumLocal.SyncSegment:output_type -> org.apache.accumulo.server.fs.pvc.wal.SyncSegmentResponse
	9,  // 28: org.apache.accumulo.server.fs.pvc.wal.WalQuorumLocal.CloseSegment:output_type -> org.apache.accumulo.server.fs.pvc.wal.CloseSegmentResponse
	11, // 29: org.apache.accumulo.server.fs.pvc.wal.WalQuorumLocal.HealthCheck:output_type -> org.apache.accumulo.server.fs.pvc.wal.HealthCheckResponse
	13, // 30: org.apache.accumulo.server.fs.pvc.wal.WalQuorumPeer.PrepareSegment:output_type -> org.apache.accumulo.server.fs.pvc.wal.PrepareSegmentResponse
	15, // 31: org.apache.accumulo.server.fs.pvc.wal.WalQuorumPeer.ReplicateEntries:output_type -> org.apache.accumulo.server.fs.pvc.wal.ReplicateEntryResponse
	17, // 32: org.apache.accumulo.server.fs.pvc.wal.WalQuorumPeer.SealSegment:output_type -> org.apache.accumulo.server.fs.pvc.wal.SealSegmentResponse
	19, // 33: org.apache.accumulo.server.fs.pvc.wal.WalQuorumPeer.ReadSegment:output_type -> org.apache.accumulo.server.fs.pvc.wal.SegmentChunk
	21, // 34: org.apache.accumulo.server.fs.pvc.wal.WalQuorumPeer.ListSegments:output_type -> org.apache.accumulo.server.fs.pvc.wal.ListSegmentsResponse
	24, // 35: org.apache.accumulo.server.fs.pvc.wal.WalQuorumPeer.PurgeSegment:output_type -> org.apache.accumulo.server.fs.pvc.wal.PurgeSegmentResponse
	25, // [25:36] is the sub-list for method output_type
	14, // [14:25] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_wal_quorum_service_proto_init() }
func file_wal_quorum_service_proto_init() {
	if File_wal_quorum_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_wal_quorum_service_proto_rawDesc), len(file_wal_quorum_service_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_wal_quorum_service_proto_goTypes,
		DependencyIndexes: file_wal_quorum_service_proto_depIdxs,
		EnumInfos:         file_wal_quorum_service_proto_enumTypes,
		MessageInfos:      file_wal_quorum_service_proto_msgTypes,
	}.Build()
	File_wal_quorum_service_proto = out.File
	file_wal_quorum_service_proto_goTypes = nil
	file_wal_quorum_service_proto_depIdxs = nil
}
