//
// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.
//

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: wal_quorum_service.proto

package qwalpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WalQuorumLocal_OpenSegment_FullMethodName  = "/org.apache.accumulo.server.fs.pvc.wal.WalQuorumLocal/OpenSegment"
	WalQuorumLocal_WriteEntries_FullMethodName = "/org.apache.accumulo.server.fs.pvc.wal.WalQuorumLocal/WriteEntries"
	WalQuorumLocal_SyncSegment_FullMethodName  = "/org.apache.accumulo.server.fs.pvc.wal.WalQuorumLocal/SyncSegment"
	WalQuorumLocal_CloseSegment_FullMethodName = "/org.apache.accumulo.server.fs.pvc.wal.WalQuorumLocal/CloseSegment"
	WalQuorumLocal_HealthCheck_FullMethodName  = "/org.apache.accumulo.server.fs.pvc.wal.WalQuorumLocal/HealthCheck"
)

// WalQuorumLocalClient is the client API for WalQuorumLocal service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ---------------------------------------------------------------------------
// WalQuorumLocal — TServer <-> sidecar communication over Unix domain socket.
// ---------------------------------------------------------------------------
type WalQuorumLocalClient interface {
	// Open a new WAL segment for writing.
	OpenSegment(ctx context.Context, in *OpenSegmentRequest, opts ...grpc.CallOption) (*OpenSegmentResponse, error)
	// Bidirectional stream: TServer streams WAL bytes, sidecar streams acks
	// after quorum write has been confirmed.
	WriteEntries(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[WriteEntryRequest, WriteEntryResponse], error)
	// Block until a quorum of replicas have called fdatasync for the segment.
	SyncSegment(ctx context.Context, in *SyncSegmentRequest, opts ...grpc.CallOption) (*SyncSegmentResponse, error)
	// Seal the segment (no more writes) and trigger async GCS upload.
	CloseSegment(ctx context.Context, in *CloseSegmentRequest, opts ...grpc.CallOption) (*CloseSegmentResponse, error)
	// Health probe for readiness/liveness checks.
	HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
}

type walQuorumLocalClient struct {
	cc grpc.ClientConnInterface
}

func NewWalQuorumLocalClient(cc grpc.ClientConnInterface) WalQuorumLocalClient {
	return &walQuorumLocalClient{cc}
}

func (c *walQuorumLocalClient) OpenSegment(ctx context.Context, in *OpenSegmentRequest, opts ...grpc.CallOption) (*OpenSegmentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OpenSegmentResponse)
	err := c.cc.Invoke(ctx, WalQuorumLocal_OpenSegment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walQuorumLocalClient) WriteEntries(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[WriteEntryRequest, WriteEntryResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &WalQuorumLocal_ServiceDesc.Streams[0], WalQuorumLocal_WriteEntries_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WriteEntryRequest, WriteEntryResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WalQuorumLocal_WriteEntriesClient = grpc.BidiStreamingClient[WriteEntryRequest, WriteEntryResponse]

func (c *walQuorumLocalClient) SyncSegment(ctx context.Context, in *SyncSegmentRequest, opts ...grpc.CallOption) (*SyncSegmentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SyncSegmentResponse)
	err := c.cc.Invoke(ctx, WalQuorumLocal_SyncSegment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walQuorumLocalClient) CloseSegment(ctx context.Context, in *CloseSegmentRequest, opts ...grpc.CallOption) (*CloseSegmentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CloseSegmentResponse)
	err := c.cc.Invoke(ctx, WalQuorumLocal_CloseSegment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walQuorumLocalClient) HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, WalQuorumLocal_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WalQuorumLocalServer is the server API for WalQuorumLocal service.
// All implementations must embed UnimplementedWalQuorumLocalServer
// for forward compatibility.
//
// ---------------------------------------------------------------------------
// WalQuorumLocal — TServer <-> sidecar communication over Unix domain socket.
// ---------------------------------------------------------------------------
type WalQuorumLocalServer interface {
	// Open a new WAL segment for writing.
	OpenSegment(context.Context, *OpenSegmentRequest) (*OpenSegmentResponse, error)
	// Bidirectional stream: TServer streams WAL bytes, sidecar streams acks
	// after quorum write has been confirmed.
	WriteEntries(grpc.BidiStreamingServer[WriteEntryRequest, WriteEntryResponse]) error
	// Block until a quorum of replicas have called fdatasync for the segment.
	SyncSegment(context.Context, *SyncSegmentRequest) (*SyncSegmentResponse, error)
	// Seal the segment (no more writes) and trigger async GCS upload.
	CloseSegment(context.Context, *CloseSegmentRequest) (*CloseSegmentResponse, error)
	// Health probe for readiness/liveness checks.
	HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
	mustEmbedUnimplementedWalQuorumLocalServer()
}

// UnimplementedWalQuorumLocalServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWalQuorumLocalServer struct{}

func (UnimplementedWalQuorumLocalServer) OpenSegment(context.Context, *OpenSegmentRequest) (*OpenSegmentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method OpenSegment not implemented")
}
func (UnimplementedWalQuorumLocalServer) WriteEntries(grpc.BidiStreamingServer[WriteEntryRequest, WriteEntryResponse]) error {
	return status.Error(codes.Unimplemented, "method WriteEntries not implemented")
}
func (UnimplementedWalQuorumLocalServer) SyncSegment(context.Context, *SyncSegmentRequest) (*SyncSegmentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SyncSegment not implemented")
}
func (UnimplementedWalQuorumLocalServer) CloseSegment(context.Context, *CloseSegmentRequest) (*CloseSegmentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CloseSegment not implemented")
}
func (UnimplementedWalQuorumLocalServer) HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedWalQuorumLocalServer) mustEmbedUnimplementedWalQuorumLocalServer() {}
func (UnimplementedWalQuorumLocalServer) testEmbeddedByValue()                        {}

// UnsafeWalQuorumLocalServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WalQuorumLocalServer will
// result in compilation errors.
type UnsafeWalQuorumLocalServer interface {
	mustEmbedUnimplementedWalQuorumLocalServer()
}

func RegisterWalQuorumLocalServer(s grpc.ServiceRegistrar, srv WalQuorumLocalServer) {
	// If the following call panics, it indicates UnimplementedWalQuorumLocalServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WalQuorumLocal_ServiceDesc, srv)
}

func _WalQuorumLocal_OpenSegment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OpenSegmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalQuorumLocalServer).OpenSegment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WalQuorumLocal_OpenSegment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalQuorumLocalServer).OpenSegment(ctx, req.(*OpenSegmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalQuorumLocal_WriteEntries_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(WalQuorumLocalServer).WriteEntries(&grpc.GenericServerStream[WriteEntryRequest, WriteEntryResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WalQuorumLocal_WriteEntriesServer = grpc.BidiStreamingServer[WriteEntryRequest, WriteEntryResponse]

func _WalQuorumLocal_SyncSegment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncSegmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalQuorumLocalServer).SyncSegment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WalQuorumLocal_SyncSegment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalQuorumLocalServer).SyncSegment(ctx, req.(*SyncSegmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalQuorumLocal_CloseSegment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CloseSegmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalQuorumLocalServer).CloseSegment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WalQuorumLocal_CloseSegment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalQuorumLocalServer).CloseSegment(ctx, req.(*CloseSegmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalQuorumLocal_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalQuorumLocalServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WalQuorumLocal_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalQuorumLocalServer).HealthCheck(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WalQuorumLocal_ServiceDesc is the grpc.ServiceDesc for WalQuorumLocal service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WalQuorumLocal_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "org.apache.accumulo.server.fs.pvc.wal.WalQuorumLocal",
	HandlerType: (*WalQuorumLocalServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "OpenSegment",
			Handler:    _WalQuorumLocal_OpenSegment_Handler,
		},
		{
			MethodName: "SyncSegment",
			Handler:    _WalQuorumLocal_SyncSegment_Handler,
		},
		{
			MethodName: "CloseSegment",
			Handler:    _WalQuorumLocal_CloseSegment_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _WalQuorumLocal_HealthCheck_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WriteEntries",
			Handler:       _WalQuorumLocal_WriteEntries_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "wal_quorum_service.proto",
}

const (
	WalQuorumPeer_PrepareSegment_FullMethodName   = "/org.apache.accumulo.server.fs.pvc.wal.WalQuorumPeer/PrepareSegment"
	WalQuorumPeer_ReplicateEntries_FullMethodName = "/org.apache.accumulo.server.fs.pvc.wal.WalQuorumPeer/ReplicateEntries"
	WalQuorumPeer_SealSegment_FullMethodName      = "/org.apache.accumulo.server.fs.pvc.wal.WalQuorumPeer/SealSegment"
	WalQuorumPeer_ReadSegment_FullMethodName      = "/org.apache.accumulo.server.fs.pvc.wal.WalQuorumPeer/ReadSegment"
	WalQuorumPeer_ListSegments_FullMethodName     = "/org.apache.accumulo.server.fs.pvc.wal.WalQuorumPeer/ListSegments"
	WalQuorumPeer_PurgeSegment_FullMethodName     = "/org.apache.accumulo.server.fs.pvc.wal.WalQuorumPeer/PurgeSegment"
)

// WalQuorumPeerClient is the client API for WalQuorumPeer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ---------------------------------------------------------------------------
// WalQuorumPeer — sidecar <-> sidecar communication over TCP port 9710.
// ---------------------------------------------------------------------------
type WalQuorumPeerClient interface {
	// Prepare a replica segment on this peer (creates file, reserves space).
	PrepareSegment(ctx context.Context, in *PrepareSegmentRequest, opts ...grpc.CallOption) (*PrepareSegmentResponse, error)
	// Bidirectional replication stream: originator sends entries, peer acks.
	ReplicateEntries(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ReplicateEntryRequest, ReplicateEntryResponse], error)
	// Seal a replica segment; peer verifies final checksum matches.
	SealSegment(ctx context.Context, in *SealSegmentRequest, opts ...grpc.CallOption) (*SealSegmentResponse, error)
	// Stream a segment back to the caller (used during recovery reads).
	ReadSegment(ctx context.Context, in *ReadSegmentRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SegmentChunk], error)
	// List all segments held on this peer.
	ListSegments(ctx context.Context, in *ListSegmentsRequest, opts ...grpc.CallOption) (*ListSegmentsResponse, error)
	// Delete a segment that has been durably uploaded to GCS.
	PurgeSegment(ctx context.Context, in *PurgeSegmentRequest, opts ...grpc.CallOption) (*PurgeSegmentResponse, error)
}

type walQuorumPeerClient struct {
	cc grpc.ClientConnInterface
}

func NewWalQuorumPeerClient(cc grpc.ClientConnInterface) WalQuorumPeerClient {
	return &walQuorumPeerClient{cc}
}

func (c *walQuorumPeerClient) PrepareSegment(ctx context.Context, in *PrepareSegmentRequest, opts ...grpc.CallOption) (*PrepareSegmentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PrepareSegmentResponse)
	err := c.cc.Invoke(ctx, WalQuorumPeer_PrepareSegment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walQuorumPeerClient) ReplicateEntries(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ReplicateEntryRequest, ReplicateEntryResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &WalQuorumPeer_ServiceDesc.Streams[0], WalQuorumPeer_ReplicateEntries_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ReplicateEntryRequest, ReplicateEntryResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WalQuorumPeer_ReplicateEntriesClient = grpc.BidiStreamingClient[ReplicateEntryRequest, ReplicateEntryResponse]

func (c *walQuorumPeerClient) SealSegment(ctx context.Context, in *SealSegmentRequest, opts ...grpc.CallOption) (*SealSegmentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SealSegmentResponse)
	err := c.cc.Invoke(ctx, WalQuorumPeer_SealSegment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walQuorumPeerClient) ReadSegment(ctx context.Context, in *ReadSegmentRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SegmentChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &WalQuorumPeer_ServiceDesc.Streams[1], WalQuorumPeer_ReadSegment_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ReadSegmentRequest, SegmentChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WalQuorumPeer_ReadSegmentClient = grpc.ServerStreamingClient[SegmentChunk]

func (c *walQuorumPeerClient) ListSegments(ctx context.Context, in *ListSegmentsRequest, opts ...grpc.CallOption) (*ListSegmentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSegmentsResponse)
	err := c.cc.Invoke(ctx, WalQuorumPeer_ListSegments_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walQuorumPeerClient) PurgeSegment(ctx context.Context, in *PurgeSegmentRequest, opts ...grpc.CallOption) (*PurgeSegmentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PurgeSegmentResponse)
	err := c.cc.Invoke(ctx, WalQuorumPeer_PurgeSegment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WalQuorumPeerServer is the server API for WalQuorumPeer service.
// All implementations must embed UnimplementedWalQuorumPeerServer
// for forward compatibility.
//
// ---------------------------------------------------------------------------
// WalQuorumPeer — sidecar <-> sidecar communication over TCP port 9710.
// ---------------------------------------------------------------------------
type WalQuorumPeerServer interface {
	// Prepare a replica segment on this peer (creates file, reserves space).
	PrepareSegment(context.Context, *PrepareSegmentRequest) (*PrepareSegmentResponse, error)
	// Bidirectional replication stream: originator sends entries, peer acks.
	ReplicateEntries(grpc.BidiStreamingServer[ReplicateEntryRequest, ReplicateEntryResponse]) error
	// Seal a replica segment; peer verifies final checksum matches.
	SealSegment(context.Context, *SealSegmentRequest) (*SealSegmentResponse, error)
	// Stream a segment back to the caller (used during recovery reads).
	ReadSegment(*ReadSegmentRequest, grpc.ServerStreamingServer[SegmentChunk]) error
	// List all segments held on this peer.
	ListSegments(context.Context, *ListSegmentsRequest) (*ListSegmentsResponse, error)
	// Delete a segment that has been durably uploaded to GCS.
	PurgeSegment(context.Context, *PurgeSegmentRequest) (*PurgeSegmentResponse, error)
	mustEmbedUnimplementedWalQuorumPeerServer()
}

// UnimplementedWalQuorumPeerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWalQuorumPeerServer struct{}

func (UnimplementedWalQuorumPeerServer) PrepareSegment(context.Context, *PrepareSegmentRequest) (*PrepareSegmentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PrepareSegment not implemented")
}
func (UnimplementedWalQuorumPeerServer) ReplicateEntries(grpc.BidiStreamingServer[ReplicateEntryRequest, ReplicateEntryResponse]) error {
	return status.Error(codes.Unimplemented, "method ReplicateEntries not implemented")
}
func (UnimplementedWalQuorumPeerServer) SealSegment(context.Context, *SealSegmentRequest) (*SealSegmentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SealSegment not implemented")
}
func (UnimplementedWalQuorumPeerServer) ReadSegment(*ReadSegmentRequest, grpc.ServerStreamingServer[SegmentChunk]) error {
	return status.Error(codes.Unimplemented, "method ReadSegment not implemented")
}
func (UnimplementedWalQuorumPeerServer) ListSegments(context.Context, *ListSegmentsRequest) (*ListSegmentsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSegments not implemented")
}
func (UnimplementedWalQuorumPeerServer) PurgeSegment(context.Context, *PurgeSegmentRequest) (*PurgeSegmentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PurgeSegment not implemented")
}
func (UnimplementedWalQuorumPeerServer) mustEmbedUnimplementedWalQuorumPeerServer() {}
func (UnimplementedWalQuorumPeerServer) testEmbeddedByValue()                       {}

// UnsafeWalQuorumPeerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WalQuorumPeerServer will
// result in compilation errors.
type UnsafeWalQuorumPeerServer interface {
	mustEmbedUnimplementedWalQuorumPeerServer()
}

func RegisterWalQuorumPeerServer(s grpc.ServiceRegistrar, srv WalQuorumPeerServer) {
	// If the following call panics, it indicates UnimplementedWalQuorumPeerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WalQuorumPeer_ServiceDesc, srv)
}

func _WalQuorumPeer_PrepareSegment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrepareSegmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalQuorumPeerServer).PrepareSegment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WalQuorumPeer_PrepareSegment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalQuorumPeerServer).PrepareSegment(ctx, req.(*PrepareSegmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalQuorumPeer_ReplicateEntries_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(WalQuorumPeerServer).ReplicateEntries(&grpc.GenericServerStream[ReplicateEntryRequest, ReplicateEntryResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WalQuorumPeer_ReplicateEntriesServer = grpc.BidiStreamingServer[ReplicateEntryRequest, ReplicateEntryResponse]

func _WalQuorumPeer_SealSegment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SealSegmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalQuorumPeerServer).SealSegment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WalQuorumPeer_SealSegment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalQuorumPeerServer).SealSegment(ctx, req.(*SealSegmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalQuorumPeer_ReadSegment_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ReadSegmentRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(WalQuorumPeerServer).ReadSegment(m, &grpc.GenericServerStream[ReadSegmentRequest, SegmentChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WalQuorumPeer_ReadSegmentServer = grpc.ServerStreamingServer[SegmentChunk]

func _WalQuorumPeer_ListSegments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSegmentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalQuorumPeerServer).ListSegments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WalQuorumPeer_ListSegments_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalQuorumPeerServer).ListSegments(ctx, req.(*ListSegmentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalQuorumPeer_PurgeSegment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PurgeSegmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalQuorumPeerServer).PurgeSegment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WalQuorumPeer_PurgeSegment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalQuorumPeerServer).PurgeSegment(ctx, req.(*PurgeSegmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WalQuorumPeer_ServiceDesc is the grpc.ServiceDesc for WalQuorumPeer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WalQuorumPeer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "org.apache.accumulo.server.fs.pvc.wal.WalQuorumPeer",
	HandlerType: (*WalQuorumPeerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PrepareSegment",
			Handler:    _WalQuorumPeer_PrepareSegment_Handler,
		},
		{
			MethodName: "SealSegment",
			Handler:    _WalQuorumPeer_SealSegment_Handler,
		},
		{
			MethodName: "ListSegments",
			Handler:    _WalQuorumPeer_ListSegments_Handler,
		},
		{
			MethodName: "PurgeSegment",
			Handler:    _WalQuorumPeer_PurgeSegment_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ReplicateEntries",
			Handler:       _WalQuorumPeer_ReplicateEntries_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "ReadSegment",
			Handler:       _WalQuorumPeer_ReadSegment_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "wal_quorum_service.proto",
}
